# Generated by Django 4.1.6 on 2023-02-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderCar",
            new_name="OrderItem",
        ),
        migrations.RenameModel(
            old_name="Car",
            new_name="Product",
        ),
    ]
