# Generated by Django 4.1 on 2023-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_store", "0004_rename_car_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
