# Generated by Django 4.1 on 2023-02-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental_store", "0007_shippingaddress_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="state",
            new_name="county",
        ),
    ]
