# Generated by Django 4.1 on 2023-02-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental_store", "0009_rename_county_shippingaddress_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="state",
            new_name="county",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="phone_number",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
